"""Fix subproducto relationship in PedidoItem

Revision ID: 3c221bd1cc56
Revises: 
Create Date: 2025-06-06 00:21:58.150834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c221bd1cc56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=True),
    sa.Column('alias', sa.String(length=80), nullable=True),
    sa.Column('tipo_cliente', sa.Enum('PUBLICO', 'COCINA', 'LEAL', 'ALIADO', 'MAYOREO', 'EMPLEADO', 'GENERICO_MOSTRADOR', name='tipocliente'), nullable=False),
    sa.Column('notas_cliente', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_alias'), ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_apellidos'), ['apellidos'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_tipo_cliente'), ['tipo_cliente'], unique=False)

    op.create_table('configuracion_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_negocio', sa.String(length=150), nullable=False),
    sa.Column('direccion_negocio', sa.String(length=255), nullable=True),
    sa.Column('telefono_negocio', sa.String(length=50), nullable=True),
    sa.Column('rfc_negocio', sa.String(length=13), nullable=True),
    sa.Column('limite_items_pa_sin_comision', sa.Integer(), nullable=False),
    sa.Column('monto_comision_fija_pa_extra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mensaje_whatsapp_confirmacion', sa.Text(), nullable=True),
    sa.Column('porcentaje_iva', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('permitir_venta_sin_stock', sa.Boolean(), nullable=False),
    sa.Column('ultimo_folio_pedido', sa.Integer(), nullable=False),
    sa.CheckConstraint('id = 1', name='chk_single_row_config'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_modif', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modificaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modificaciones_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_modificaciones_codigo_modif'), ['codigo_modif'], unique=True)
        batch_op.create_index(batch_op.f('ix_modificaciones_nombre'), ['nombre'], unique=False)

    op.create_table('productos',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_nombre'), ['nombre'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('rol', sa.Enum('ADMINISTRADOR', 'CAJERO', 'TABLAJERO', 'REPARTIDOR', name='rolusuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_rol'), ['rol'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)

    op.create_table('cortes_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id_responsable', sa.Integer(), nullable=False),
    sa.Column('fecha_apertura_periodo', sa.DateTime(), nullable=False),
    sa.Column('fecha_cierre_corte', sa.DateTime(), nullable=False),
    sa.Column('saldo_inicial_efectivo_teorico', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_ingresos_efectivo_periodo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_egresos_efectivo_periodo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('saldo_final_efectivo_teorico', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('saldo_final_efectivo_contado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('diferencia_efectivo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_ingresos_tarjeta_periodo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_ingresos_transfer_periodo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_ingresos_otros_periodo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado_corte', sa.Enum('ABIERTO', 'CERRADO_CONCILIADO', 'CERRADO_CON_DIFERENCIA', name='estadocortecaja'), nullable=False),
    sa.Column('notas_corte', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id_responsable'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cortes_caja', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cortes_caja_diferencia_efectivo'), ['diferencia_efectivo'], unique=False)
        batch_op.create_index(batch_op.f('ix_cortes_caja_estado_corte'), ['estado_corte'], unique=False)
        batch_op.create_index(batch_op.f('ix_cortes_caja_fecha_apertura_periodo'), ['fecha_apertura_periodo'], unique=False)
        batch_op.create_index(batch_op.f('ix_cortes_caja_fecha_cierre_corte'), ['fecha_cierre_corte'], unique=False)
        batch_op.create_index(batch_op.f('ix_cortes_caja_usuario_id_responsable'), ['usuario_id_responsable'], unique=False)

    op.create_table('direcciones_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('calle_numero', sa.String(length=200), nullable=False),
    sa.Column('colonia', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('codigo_postal', sa.String(length=10), nullable=True),
    sa.Column('referencias', sa.Text(), nullable=True),
    sa.Column('tipo_direccion', sa.Enum('CASA', 'NEGOCIO', 'ENTREGA_PRINCIPAL', name='tipodireccion'), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('direcciones_cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_direcciones_cliente_ciudad'), ['ciudad'], unique=False)
        batch_op.create_index(batch_op.f('ix_direcciones_cliente_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_direcciones_cliente_codigo_postal'), ['codigo_postal'], unique=False)
        batch_op.create_index(batch_op.f('ix_direcciones_cliente_colonia'), ['colonia'], unique=False)
        batch_op.create_index(batch_op.f('ix_direcciones_cliente_es_principal'), ['es_principal'], unique=False)
        batch_op.create_index(batch_op.f('ix_direcciones_cliente_tipo_direccion'), ['tipo_direccion'], unique=False)

    op.create_table('producto_modificacion_association',
    sa.Column('producto_id', sa.String(length=10), nullable=False),
    sa.Column('modificacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modificacion_id'], ['modificaciones.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'modificacion_id')
    )
    op.create_table('subproductos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_padre_id', sa.String(length=10), nullable=False),
    sa.Column('codigo_subprod', sa.String(length=15), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['producto_padre_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subproductos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subproductos_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_subproductos_codigo_subprod'), ['codigo_subprod'], unique=True)
        batch_op.create_index(batch_op.f('ix_subproductos_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_subproductos_producto_padre_id'), ['producto_padre_id'], unique=False)

    op.create_table('telefonos_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('numero_telefono', sa.String(length=20), nullable=False),
    sa.Column('tipo_telefono', sa.Enum('CELULAR', 'WHATSAPP', 'CASA', 'NEGOCIO', name='tipotelefono'), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'numero_telefono', name='uq_cliente_numero_telefono')
    )
    with op.batch_alter_table('telefonos_cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telefonos_cliente_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telefonos_cliente_es_principal'), ['es_principal'], unique=False)
        batch_op.create_index(batch_op.f('ix_telefonos_cliente_numero_telefono'), ['numero_telefono'], unique=False)
        batch_op.create_index(batch_op.f('ix_telefonos_cliente_tipo_telefono'), ['tipo_telefono'], unique=False)

    op.create_table('corte_caja_denominaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corte_caja_id', sa.Integer(), nullable=False),
    sa.Column('denominacion_valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cantidad_contada', sa.Integer(), nullable=False),
    sa.Column('total_por_denominacion', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['corte_caja_id'], ['cortes_caja.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corte_caja_id', 'denominacion_valor', name='uq_corte_denominacion_detalle')
    )
    with op.batch_alter_table('corte_caja_denominaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corte_caja_denominaciones_corte_caja_id'), ['corte_caja_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corte_caja_denominaciones_denominacion_valor'), ['denominacion_valor'], unique=False)

    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('repartidor_id', sa.Integer(), nullable=True),
    sa.Column('direccion_entrega_id', sa.Integer(), nullable=True),
    sa.Column('tipo_venta', sa.Enum('MOSTRADOR', 'DOMICILIO', name='tipoventa'), nullable=False),
    sa.Column('forma_pago', sa.Enum('EFECTIVO', 'TARJETA_DEBITO', 'TARJETA_CREDITO', 'TRANSFERENCIA_BANCARIA', 'QR_PAGO', 'CREDITO_INTERNO', 'CORTESIA', 'PAGO_MULTIPLE', 'GASTO_INTERNO_CAJA', 'AJUSTE_INGRESO_CAJA', 'AJUSTE_EGRESO_CAJA', 'SALDO_INICIAL_CAJA', 'RETIRO_EFECTIVO_CAJA', 'EFECTIVO_CONTRA_ENTREGA', name='formapago'), nullable=True),
    sa.Column('paga_con', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cambio_entregado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('subtotal_productos_pollo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal_productos_adicionales', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento_aplicado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_envio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_pedido', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado_pedido', sa.Enum('PENDIENTE_CONFIRMACION', 'PENDIENTE_PREPARACION', 'EN_PREPARACION', 'LISTO_PARA_ENTREGA', 'ASIGNADO_A_REPARTIDOR', 'EN_RUTA', 'ENTREGADO_PENDIENTE_PAGO', 'ENTREGADO_Y_PAGADO', 'PAGADO', 'PROBLEMA_EN_ENTREGA', 'REPROGRAMADO', 'CANCELADO_POR_CLIENTE', 'CANCELADO_POR_NEGOCIO', name='estadopedido'), nullable=False),
    sa.Column('notas_pedido', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_entrega_programada', sa.DateTime(), nullable=True),
    sa.Column('requiere_factura', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['direccion_entrega_id'], ['direcciones_cliente.id'], ),
    sa.ForeignKeyConstraint(['repartidor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_direccion_entrega_id'), ['direccion_entrega_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_estado_pedido'), ['estado_pedido'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_fecha_actualizacion'), ['fecha_actualizacion'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_fecha_creacion'), ['fecha_creacion'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_fecha_entrega_programada'), ['fecha_entrega_programada'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_forma_pago'), ['forma_pago'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_repartidor_id'), ['repartidor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_tipo_venta'), ['tipo_venta'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_total_pedido'), ['total_pedido'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('precios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.String(length=10), nullable=True),
    sa.Column('subproducto_id', sa.Integer(), nullable=True),
    sa.Column('tipo_cliente', sa.Enum('PUBLICO', 'COCINA', 'LEAL', 'ALIADO', 'MAYOREO', 'EMPLEADO', 'GENERICO_MOSTRADOR', name='tipocliente'), nullable=False),
    sa.Column('precio_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cantidad_minima_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('etiqueta_promo', sa.String(length=100), nullable=True),
    sa.Column('fecha_inicio_vigencia', sa.Date(), nullable=True),
    sa.Column('fecha_fin_vigencia', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(producto_id IS NOT NULL AND subproducto_id IS NULL) OR (producto_id IS NULL AND subproducto_id IS NOT NULL)', name='chk_precio_target'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['subproducto_id'], ['subproductos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'tipo_cliente', 'cantidad_minima_kg', name='uq_precio_prod'),
    sa.UniqueConstraint('subproducto_id', 'tipo_cliente', 'cantidad_minima_kg', name='uq_precio_subprod')
    )
    with op.batch_alter_table('precios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_precios_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_precios_cantidad_minima_kg'), ['cantidad_minima_kg'], unique=False)
        batch_op.create_index(batch_op.f('ix_precios_fecha_fin_vigencia'), ['fecha_fin_vigencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_precios_fecha_inicio_vigencia'), ['fecha_inicio_vigencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_precios_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_precios_subproducto_id'), ['subproducto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_precios_tipo_cliente'), ['tipo_cliente'], unique=False)

    op.create_table('subproducto_modificacion_association',
    sa.Column('subproducto_id', sa.Integer(), nullable=False),
    sa.Column('modificacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modificacion_id'], ['modificaciones.id'], ),
    sa.ForeignKeyConstraint(['subproducto_id'], ['subproductos.id'], ),
    sa.PrimaryKeyConstraint('subproducto_id', 'modificacion_id')
    )
    op.create_table('movimientos_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('corte_caja_id', sa.Integer(), nullable=True),
    sa.Column('tipo_movimiento', sa.Enum('INGRESO', 'EGRESO', name='tipomovimientocaja'), nullable=False),
    sa.Column('motivo_movimiento', sa.String(length=255), nullable=False),
    sa.Column('monto_movimiento', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma_pago_efectuado', sa.Enum('EFECTIVO', 'TARJETA_DEBITO', 'TARJETA_CREDITO', 'TRANSFERENCIA_BANCARIA', 'QR_PAGO', 'CREDITO_INTERNO', 'CORTESIA', 'PAGO_MULTIPLE', 'GASTO_INTERNO_CAJA', 'AJUSTE_INGRESO_CAJA', 'AJUSTE_EGRESO_CAJA', 'SALDO_INICIAL_CAJA', 'RETIRO_EFECTIVO_CAJA', 'EFECTIVO_CONTRA_ENTREGA', name='formapago'), nullable=False),
    sa.Column('fecha_movimiento', sa.DateTime(), nullable=False),
    sa.Column('notas_movimiento', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['corte_caja_id'], ['cortes_caja.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimientos_caja', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimientos_caja_corte_caja_id'), ['corte_caja_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_caja_fecha_movimiento'), ['fecha_movimiento'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_caja_forma_pago_efectuado'), ['forma_pago_efectuado'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_caja_monto_movimiento'), ['monto_movimiento'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_caja_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_caja_tipo_movimiento'), ['tipo_movimiento'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_caja_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('pedido_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.String(length=10), nullable=True),
    sa.Column('subproducto_id', sa.Integer(), nullable=True),
    sa.Column('modificacion_id', sa.Integer(), nullable=True),
    sa.Column('descripcion_item_venta', sa.String(length=255), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unidad_medida', sa.String(length=10), nullable=False),
    sa.Column('precio_unitario_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal_item', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_unitario_item', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.CheckConstraint('(producto_id IS NOT NULL AND subproducto_id IS NULL) OR (producto_id IS NULL AND subproducto_id IS NOT NULL)', name='chk_pedidoitem_target'),
    sa.ForeignKeyConstraint(['modificacion_id'], ['modificaciones.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['subproducto_id'], ['subproductos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedido_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_items_modificacion_id'), ['modificacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_items_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_items_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_items_subproducto_id'), ['subproducto_id'], unique=False)

    op.create_table('pedido_productos_adicionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('nombre_pa', sa.String(length=150), nullable=False),
    sa.Column('cantidad_pa', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unidad_medida_pa', sa.String(length=20), nullable=False),
    sa.Column('costo_compra_unitario_pa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_venta_unitario_pa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal_pa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('comision_calculada_pa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notas_pa', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedido_productos_adicionales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_productos_adicionales_nombre_pa'), ['nombre_pa'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_productos_adicionales_pedido_id'), ['pedido_id'], unique=False)

    op.create_table('movimiento_denominaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movimiento_caja_id', sa.Integer(), nullable=False),
    sa.Column('denominacion_valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movimiento_caja_id'], ['movimientos_caja.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movimiento_caja_id', 'denominacion_valor', name='uq_movimiento_denominacion_detalle')
    )
    with op.batch_alter_table('movimiento_denominaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimiento_denominaciones_denominacion_valor'), ['denominacion_valor'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimiento_denominaciones_movimiento_caja_id'), ['movimiento_caja_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento_denominaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimiento_denominaciones_movimiento_caja_id'))
        batch_op.drop_index(batch_op.f('ix_movimiento_denominaciones_denominacion_valor'))

    op.drop_table('movimiento_denominaciones')
    with op.batch_alter_table('pedido_productos_adicionales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_productos_adicionales_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_productos_adicionales_nombre_pa'))

    op.drop_table('pedido_productos_adicionales')
    with op.batch_alter_table('pedido_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_items_subproducto_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_items_producto_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_items_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_items_modificacion_id'))

    op.drop_table('pedido_items')
    with op.batch_alter_table('movimientos_caja', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimientos_caja_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_caja_tipo_movimiento'))
        batch_op.drop_index(batch_op.f('ix_movimientos_caja_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_caja_monto_movimiento'))
        batch_op.drop_index(batch_op.f('ix_movimientos_caja_forma_pago_efectuado'))
        batch_op.drop_index(batch_op.f('ix_movimientos_caja_fecha_movimiento'))
        batch_op.drop_index(batch_op.f('ix_movimientos_caja_corte_caja_id'))

    op.drop_table('movimientos_caja')
    op.drop_table('subproducto_modificacion_association')
    with op.batch_alter_table('precios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_precios_tipo_cliente'))
        batch_op.drop_index(batch_op.f('ix_precios_subproducto_id'))
        batch_op.drop_index(batch_op.f('ix_precios_producto_id'))
        batch_op.drop_index(batch_op.f('ix_precios_fecha_inicio_vigencia'))
        batch_op.drop_index(batch_op.f('ix_precios_fecha_fin_vigencia'))
        batch_op.drop_index(batch_op.f('ix_precios_cantidad_minima_kg'))
        batch_op.drop_index(batch_op.f('ix_precios_activo'))

    op.drop_table('precios')
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_pedidos_total_pedido'))
        batch_op.drop_index(batch_op.f('ix_pedidos_tipo_venta'))
        batch_op.drop_index(batch_op.f('ix_pedidos_repartidor_id'))
        batch_op.drop_index(batch_op.f('ix_pedidos_forma_pago'))
        batch_op.drop_index(batch_op.f('ix_pedidos_fecha_entrega_programada'))
        batch_op.drop_index(batch_op.f('ix_pedidos_fecha_creacion'))
        batch_op.drop_index(batch_op.f('ix_pedidos_fecha_actualizacion'))
        batch_op.drop_index(batch_op.f('ix_pedidos_estado_pedido'))
        batch_op.drop_index(batch_op.f('ix_pedidos_direccion_entrega_id'))
        batch_op.drop_index(batch_op.f('ix_pedidos_cliente_id'))

    op.drop_table('pedidos')
    with op.batch_alter_table('corte_caja_denominaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corte_caja_denominaciones_denominacion_valor'))
        batch_op.drop_index(batch_op.f('ix_corte_caja_denominaciones_corte_caja_id'))

    op.drop_table('corte_caja_denominaciones')
    with op.batch_alter_table('telefonos_cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telefonos_cliente_tipo_telefono'))
        batch_op.drop_index(batch_op.f('ix_telefonos_cliente_numero_telefono'))
        batch_op.drop_index(batch_op.f('ix_telefonos_cliente_es_principal'))
        batch_op.drop_index(batch_op.f('ix_telefonos_cliente_cliente_id'))

    op.drop_table('telefonos_cliente')
    with op.batch_alter_table('subproductos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subproductos_producto_padre_id'))
        batch_op.drop_index(batch_op.f('ix_subproductos_nombre'))
        batch_op.drop_index(batch_op.f('ix_subproductos_codigo_subprod'))
        batch_op.drop_index(batch_op.f('ix_subproductos_activo'))

    op.drop_table('subproductos')
    op.drop_table('producto_modificacion_association')
    with op.batch_alter_table('direcciones_cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_direcciones_cliente_tipo_direccion'))
        batch_op.drop_index(batch_op.f('ix_direcciones_cliente_es_principal'))
        batch_op.drop_index(batch_op.f('ix_direcciones_cliente_colonia'))
        batch_op.drop_index(batch_op.f('ix_direcciones_cliente_codigo_postal'))
        batch_op.drop_index(batch_op.f('ix_direcciones_cliente_cliente_id'))
        batch_op.drop_index(batch_op.f('ix_direcciones_cliente_ciudad'))

    op.drop_table('direcciones_cliente')
    with op.batch_alter_table('cortes_caja', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cortes_caja_usuario_id_responsable'))
        batch_op.drop_index(batch_op.f('ix_cortes_caja_fecha_cierre_corte'))
        batch_op.drop_index(batch_op.f('ix_cortes_caja_fecha_apertura_periodo'))
        batch_op.drop_index(batch_op.f('ix_cortes_caja_estado_corte'))
        batch_op.drop_index(batch_op.f('ix_cortes_caja_diferencia_efectivo'))

    op.drop_table('cortes_caja')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))
        batch_op.drop_index(batch_op.f('ix_usuarios_rol'))
        batch_op.drop_index(batch_op.f('ix_usuarios_activo'))

    op.drop_table('usuarios')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_nombre'))
        batch_op.drop_index(batch_op.f('ix_productos_categoria'))
        batch_op.drop_index(batch_op.f('ix_productos_activo'))

    op.drop_table('productos')
    with op.batch_alter_table('modificaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modificaciones_nombre'))
        batch_op.drop_index(batch_op.f('ix_modificaciones_codigo_modif'))
        batch_op.drop_index(batch_op.f('ix_modificaciones_activo'))

    op.drop_table('modificaciones')
    op.drop_table('configuracion_sistema')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_tipo_cliente'))
        batch_op.drop_index(batch_op.f('ix_clientes_nombre'))
        batch_op.drop_index(batch_op.f('ix_clientes_apellidos'))
        batch_op.drop_index(batch_op.f('ix_clientes_alias'))
        batch_op.drop_index(batch_op.f('ix_clientes_activo'))

    op.drop_table('clientes')
    # ### end Alembic commands ###
